### ISSUE TITLE
recorded an error

### ISSUE THREAD

**Issue by PushyTao** [MrOnlineCoder/GoJudge#17]
Hello MrOnlineCoder...Firstly thanks your code. When i running code on Linux(Ubuntu22.04),after submitted a cpp code, an error was recorded:[Judge] ERROR: Couldn't write sourcecode: open sandbox/sub_3_a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3.cpp: no such file or directory
. Why?

**Comment by silves-xiang** [comment]
你好，我在搭这个项目，为什么搭建好之后，添加题目之后，再向contest中添加题目时，没有之前添加的题目

**Comment by PushyTao** [comment]
> 你好，我在搭这个项目，为什么搭建好之后，添加题目之后，再向contest中添加题目时，没有之前添加的题目

试过了，有的啊

**Comment by silves-xiang** [comment]
您好，您可以大概介绍一下搭建步骤吗

**Comment by silves-xiang** [comment]
我的大酒店步骤，打包vue文件会报错，但是还是生成了dist文件，使用nginx转发，然后后端直接编译成二进制，直接部署到

**Comment by silves-xiang** [comment]
我的服务器地址，49.234.53.11

**Comment by silves-xiang** [comment]
你这个问题，我遇到了，在可执行文件同级目录下创建sandbox文件夹

**Comment by MrOnlineCoder** [comment]
@PushyTao @silves-xiang sorry guys for not responding to you for over a year. This project was a small personal experiment in learning Go and the code itself is a mess. If you need to setup a programming contest, please use one of the mature open-source systems out there. Thanks for the attention anyway!
